spring:
  application:
    name: coupon
  datasource:
    url: jdbc:mysql://${ENDPOINT}:3306/order?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin&useServerPrepStmts=false&rewriteBatchedStatements=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


server:
  port: 7000
